### ISSUE TITLE
Build integration

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/tdwg-theme#25]
@MattBlissett I noticed that commits to the `master` in this `tdwg-theme` repository do **not** trigger a new build. Ideally they should, so that changes to either:

https://github.com/tdwg/tdwg-theme
https://github.com/tdwg/website

trigger a new build.

Is it possible to set this up?

**Comment by MattBlissett** [comment]
Done, I'd renamed the build job but not updated the webhook for this repository.
