### ISSUE TITLE
Assets served over https are blocked by CORS policy

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/tdwg-theme#7]
The dev TDWG theme is currently served at https://dev.tdwg.org/theme/css/main.css and can thus be used by satellite websites, like the new beta Darwin Core quick reference guide: http://rawgit.com/tdwg/dwc/master/www/guides/index.html

Although the CSS can be read perfectly by the guide, access to the referenced font-awesome font is blocked by **Cross-origin resource sharing policy**, I assume because the guide is served over **http** (here rawgit, but would be the same for a GitHub pages website) and is trying to access a (potentially sensitive) **https** resource:

> Access to Font at 'https://dev.tdwg.org/theme/fonts/font-awesome/fontawesome-webfont.woff2?v=4.7.0' from origin 'http://rawgit.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rawgit.com' is therefore not allowed access.
> Access to Font at 'https://dev.tdwg.org/theme/fonts/font-awesome/fontawesome-webfont.woff?v=4.7.0' from origin 'http://rawgit.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rawgit.com' is therefore not allowed access.
> Access to Font at 'https://dev.tdwg.org/theme/fonts/font-awesome/fontawesome-webfont.ttf?v=4.7.0' from origin 'http://rawgit.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rawgit.com' is therefore not allowed access.

As a result, font-awesome icons are not rendered. Other than forcing every TDWG satellite website to use https, is there anything that can be done at https://dev.tdwg.org to allow access? @MattBlissett?

Note: eventually the guide will use the production css from https://tdwg.org/theme/css/main.css, but until that is available, the dev css is used. Note, if tdwg.org will be served over https, the same error will pop up again.

**Comment by peterdesmet** [comment]
The icon for the page navigation still does not load in Chrome (but does in Safari on iOS):

> Access to font at 'https://www.tdwg.org/theme/fonts/font-awesome/fontawesome-webfont.ttf?v=4.7.0' from origin 'https://dwc.tdwg.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

@MattBlissett or others, any idea how to solve this?

**Comment by MattBlissett** [comment]
I'll add a header, using Apache:

```
Header                     set Access-Control-Allow-Origin "*"
```

I have set this only for the `/theme/fonts` directory.

**Comment by peterdesmet** [comment]
Thanks, https://dwc.tdwg.org/terms/ no longer shows the error.
